name: Deploy NestJS to EC2

on:
  push:
    branches:
      - main
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Deploy Project to EC2 via SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_VPS }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH }}
          source: "."
          target: "${{ github.ref == 'refs/heads/main' && secrets.PROJECT_PATH || secrets.PROJECT_PATH_DEV }}"
          rm: true
          strip_components: 0

      - name: Upload .env File
        uses: appleboy/ssh-action@v1.0.0
        with:
            host: ${{ secrets.EC2_VPS }}
            username: ${{ secrets.EC2_USER }}
            key: ${{ secrets.EC2_SSH }}
            script: |
                echo "${{ github.ref == 'refs/heads/main' && secrets.ENV || secrets.ENV_DEV }}" > ${{ github.ref == 'refs/heads/main' && secrets.PROJECT_PATH || secrets.PROJECT_PATH_DEV }}/.env

      - name: Run Remote Deployment Script
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_VPS }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH }}
          script: |
            PROJECT_DIR="${{ github.ref == 'refs/heads/main' && secrets.PROJECT_PATH || secrets.PROJECT_PATH_DEV }}"
            cd "$PROJECT_DIR"
            echo "Installing dependencies..."
            npm install
            npm run build
